baseurl = "https://example.org/"
languageCode = "en-us"
title = "Natrium Theme"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClassic = true

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ucarion"
    weight = -110

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
